apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlaas-watcher
  namespace: mlaas
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: mlaas-watcher
  template:
    metadata:
      labels:
        app: mlaas-watcher
    spec:
      containers:
      - image: arthurma/tree:v1.0.0
        name: watcher
        env:
        - name: POD_CATEGORY
          value: "mlaas-job"
        - name: CONTROLLER_SERVICE_URL
          value: "http://34.71.15.195:9000"
        - name: AZP_MAPPING_BRANCH
          value: "develop"
        - name: AZP_PAT
          value: "xxxxxxxxxxx"